unit Cliente;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type

  [Entity]
  [Table('CLIENTE')]
  [Sequence('SELECT GEN_ID(SEQ_CLI_ID, 1) FROM RDB$DATABASE')]
  TCliente = class
  strict private
    fId: Int64;
    fNome: string;
  public
    [AutoGenerated]
    [Column('CLI_ID', [cpPrimaryKey, cpRequired, cpNotNull])]
    property Id: Int64 read fId write fId;

    [Column('CLI_NOME', [cpRequired, cpNotNull], 60)]
    property Nome: string read fNome write fNome;
  end;

implementation

end.
