unit Produto;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type

  [Entity]
  [Table('PRODUTO')]
  [Sequence('SELECT GEN_ID(SEQ_PRO_ID, 1) FROM RDB$DATABASE')]
  TProduto = class
  strict private
    fId: Int64;
    fEan: string;
    fDescricao: string;
    fPreco: Currency;
    fCusto: Currency;
  public
    [AutoGenerated]
    [Column('PRO_ID', [cpPrimaryKey, cpRequired, cpNotNull])]
    property Id: Int64 read fId write fId;

    [Column('PRO_EAN', [cpRequired, cpNotNull], 13)]
    property Ean: string read fEan write fEan;

    [Column('PRO_DESCRICAO', [cpRequired, cpNotNull], 60)]
    property Descricao: string read fDescricao write fDescricao;

    [Column('PRO_PRECO', [cpRequired, cpNotNull])]
    property Preco: Currency read fPreco write fPreco;

    [Column('PRO_CUSTO', [cpRequired, cpNotNull])]
    property Custo: Currency read fCusto write fCusto;
  end;

implementation

end.
